### ISSUE TITLE
Is this still being maintained? (PS: awesome work)

### ISSUE THREAD

**Issue by xanoni** [sjoerdvanderhoorn/Geheim#3]
Do you still recommend using this? Noticed it hasn't been updated in 3 years. Thank you.

PS: Looks amazing, the world needs this.

**Comment by sjoerdvanderhoorn** [comment]
This is no longer under active development, but should still be functional. The **XOR (One-time pad)** method should still be as strong as three years ago, the other methods (AES using Stanford Javascript Crypto Library and RSA using JSEncrypt) should be considered weakened and may only act as a stub. Before use I would advice you to replaced them another implementation.

Pull requests will still be actively accepted.
